version: "3.3"
services:

  traefik:
    image: traefik:picodon
    environment:
      - TRAEFIK_PROVIDERS_REDIS_ENDPOINTS=redis:6379
      - TRAEFIK_PROVIDERS_REDIS_ROOTKEY=traefik
      - TRAEFIK_PROVIDERS_REDIS_PASSWORD=redispassword
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_PING_MANUALROUTING=true
      - TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_HTTP_FORWARDEDHEADERS_TRUSTEDIPS=127.0.0.1/32
      - TRAEFIK_LOG_FORMAT=common
      - TRAEFIK_LOG_LEVEL=DEBUG
    networks:
      - pylon
    ports:
      - "80:80"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - pylon
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    networks:
      - pylon

  pylon:
    build: ../pylon
    environment:
      - CORE_DEBUG_LOGGING=true
      - CORE_CONFIG_SEED=file:/config/pylon.yml
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./core/config:/config
    networks:
      - pylon
    depends_on:
      - traefik
      - redis
      - minio

volumes:
  redis-data:
  minio-data:

networks:
  pylon:
