http:
  routers:
    minio:
      rule: "PathPrefix(`/minio`) || Query(`X-Amz-SignedHeaders=host`) || HeadersRegexp(`X-Amz-Date`, `.*T.*Z`)"
      entryPoints:
      - "http"
      service: "minio"
  services:
    minio:
      loadBalancer:
        servers:
        - url: "http://minio:9000/"
