name: Build and push Docker multiarch image

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
    inputs:
        docker_tag:
          default: "getcarrier/pylon:latest"
          description: "Docker image name and tag"
          required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ inputs.docker_tag }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
      - name: Build and push Alpine
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ inputs.docker_tag }}-alpine
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.alpine